[build-system]
requires = ["scikit-build-core >=0.4.3", "nanobind >=1.3.2"]
build-backend = "scikit_build_core.build"

[project]
name = "qulacs2023"
version = "1.0.0"
description = "Quantum circuit simulator for research"
authors = [
    { name = "Qulacs-Osaka", email = "qulacs.osaka@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
dependencies = [
    "scikit_build",
    "nanobind"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Programming Language :: Python",
    "Topic :: Communications :: Email"
]

[tool.scikit-build]
minimum-version = "0.4"
# Setuptools-style build caching in a local directory
build-dir = "build/{wheel_tag}"
# Build stable ABI wheels for CPython 3.12+
wheel.py-api = "cp312"

[tool.scikit-build.cmake.define]
QULACS_USE_OMP = {env="QULACS_USE_OMP", default="Yes"}
QULACS_USE_CUDA = {env="QULACS_USE_CUDA", default="No"}
QULACS_CUDA_ARCH = {env="QULACS_CUDA_ARCH"}

[project.urls]
homepage = "http://www.qulacs.org"

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "isort",
    "mypy",
    "nanobind",
    "nanobind-stubgen",
    "openfermion"
]

test = [
    "openfermion"
]

ci = [
    "black",
    "flake8",
    "isort",
    "mypy",
    "nanobind-stubgen",
    "openfermion"
]

doc = [
    "sphinx == 4.5.0",
    "sphinx-rtd-theme == 1.0.*",
    "breathe == 4.33.*",
    "exhale == 0.3.*",
    "nbsphinx == 0.8.*",
    "myst-parser == 0.18.*",
    "sphinx-copybutton == 0.5.*",
    "ipykernel == 6.17.*",
    "sphinx-autoapi == 2.0.*"
]
