name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: actions/checkout@42
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-autoapi
    - name: Build docs
      run: make html
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
